/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Maintenance;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ajaygoel
 */
public class MaintenanceWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaintenanceWAJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organisation organization;
    Enterprise enterprise;
    Ecosystem business;


    public MaintenanceWAJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
                initComponents();
                this.userProcessContainer=userProcessContainer;
                this.account=account;
                this.organization=organization;
                this.enterprise=enterprise;
                this.business=business;
        nameTxtField.setText(account.getEmployee().getName());
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageAccountsBtn = new javax.swing.JButton();
        ManageSupAccountsJPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageAccountsBtn.setText("Manage Maintenance Requests");
        ManageAccountsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountsBtnActionPerformed(evt);
            }
        });
        add(ManageAccountsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, 682, -1));

        ManageSupAccountsJPanel.setText("Manage Accounts");
        ManageSupAccountsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSupAccountsJPanelActionPerformed(evt);
            }
        });
        add(ManageSupAccountsJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 682, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Maintenance Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 11, 236, -1));
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 15, 106, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Welcome !");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAccountsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountsBtnActionPerformed
        // TODO add your handling code here:
        
       MaintenanceRequestsWAJPanel isusajp = new MaintenanceRequestsWAJPanel(userProcessContainer,account, organization, enterprise,business);
        userProcessContainer.add("MaintenanceRequestsWAJPanel",isusajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ManageAccountsBtnActionPerformed

    private void ManageSupAccountsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSupAccountsJPanelActionPerformed
        // TODO add your handling code here:
            MaintenanceAccountsJPanel isusajp = new MaintenanceAccountsJPanel(userProcessContainer,account, organization, enterprise,business);
        userProcessContainer.add("MaintenanceAccountsJPanel",isusajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        

    }//GEN-LAST:event_ManageSupAccountsJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAccountsBtn;
    private javax.swing.JButton ManageSupAccountsJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTxtField;
    // End of variables declaration//GEN-END:variables
}
