/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Water;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Interface.Electricity.ManageElectricityRequestJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Himani Solanki
 */
public class WaterWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WaterWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organisation organization;
    Enterprise enterprise;
    Ecosystem business;
    UserAccount account1;

    public WaterWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Organisation organization, Ecosystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.business=business;
        this.organization= organization;
        this.account1= account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageWaterRequestButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Water Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 21, -1, -1));

        manageWaterRequestButton.setText("Manage Water Request");
        manageWaterRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWaterRequestButtonActionPerformed(evt);
            }
        });
        add(manageWaterRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 102, 194, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/water.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageWaterRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWaterRequestButtonActionPerformed
        // TODO add your handling code here:
        Interface.Water.ManageWaterRequestJPanel isusajp = new Interface.Water.ManageWaterRequestJPanel(userProcessContainer, enterprise,business,account1);
        userProcessContainer.add("ManageWaterRequestJPanel",isusajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageWaterRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageWaterRequestButton;
    // End of variables declaration//GEN-END:variables
}
