/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Electricity;

import Business.Customer.Customer;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Organisation.ElectricityOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ElectricityWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Himani Solanki
 */
public class ManageElectricityRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageElectricityRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organisation organization;
    Enterprise enterprise;
    Ecosystem business;
    Customer customer;
    ElectricityOrganisation electricityOrganisation;
    //int charge=5;
    int cost_10_days=1;
    int cost_after_10_days=2;
    
    ManageElectricityRequestJPanel(JPanel userProcessContainer,Enterprise enterprise,Ecosystem business, UserAccount account ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.business=business;
        jSlider1.setValue(cost_10_days);
        jSlider2.setValue(cost_after_10_days);
        SliderValue.setText(String.valueOf(cost_10_days));
        SliderValue2.setText(String.valueOf(cost_after_10_days));
        
      //  chargeTextField.setText(String.valueOf(charge));
        
        for(Network n:business.getNetworkDirectory())
        {
            for(Enterprise enterprise1 :n.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organisation org:enterprise1.getOrganisationDirectory().getOrganizationlist())
                {
                    if (org instanceof ElectricityOrganisation)
            
                    {   
                            electricityOrganisation=(ElectricityOrganisation) org;
                            break;
                    }
                }
            }
        }
        populateTable();
    }
       
    private void populateTable()
    {
        
        DefaultTableModel dtm = (DefaultTableModel) receReqJTbl.getModel();
        dtm.setRowCount(0);
        
        for (Iterator<WorkRequest> it = electricityOrganisation.getWorkQueue().getReqList().iterator(); it.hasNext();) {
          //  UserAccount rec = wr.getReceiver();
             ElectricityWorkRequest wr = (ElectricityWorkRequest) it.next();
             {
                Object Row[] = new Object[5];
                Row[0] = wr.getCust();
                Row[1] = wr.getRequestDate();
                Row[2] = wr.getMessage();
                Row[3] = wr;
                Row[4] = wr.getReqCharges();

                dtm.addRow(Row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receReqJTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        closeBillButton = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SliderValue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SliderValue2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackJBtn.setText("<< Back");
        BackJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBtnActionPerformed(evt);
            }
        });
        add(BackJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Enterprise Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 21, -1, -1));

        receReqJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Detail", "Request Date", "Request Message", "Status", "Total Charges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(receReqJTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 93, 709, 97));

        jLabel2.setText("Per Unit Charge first 10 days");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 202, -1, 24));

        closeBillButton.setText("Close Bill");
        closeBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBillButtonActionPerformed(evt);
            }
        });
        add(closeBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 201, 252, -1));

        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSlider1MouseMoved(evt);
            }
        });
        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));
        add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel3.setText("Per Unit Charge after 10 days");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 257, -1, -1));

        jLabel4.setText("0");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        SliderValue.setText("50");
        add(SliderValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel6.setText("100");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel7.setText("100");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        SliderValue2.setText("50");
        add(SliderValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel9.setText("0");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bills.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackJBtnActionPerformed

    private void closeBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBillButtonActionPerformed
        // TODO add your handling code here:
        int row = receReqJTbl.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ElectricityWorkRequest wr= (ElectricityWorkRequest)receReqJTbl.getValueAt(row, 3);
        Customer customer =(Customer) receReqJTbl.getValueAt(row, 0);
        if (wr.getStatus().equals("CLOSED")) {
            JOptionPane.showMessageDialog(null, "This request has already been closed", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        wr.setStatus("CLOSED");
        wr.setMessage("The Electricity request have been successfully closed. Please contact water admin for any issue.");
        Date resolveDate= new Date();
        wr.setResolveDate(resolveDate);
        wr.setReceiver(account);
        
        
        double cost;
        int days = wr.getCust().getElectricity().getElecDays();
        if(days<11)
        {
            cost=days*cost_10_days;
        }
        else
        {
            cost=(10*cost_10_days)+((days-10)*cost_after_10_days);
        }
        //cost=charge*wr.getCust().getElectricity().getElecDays();
        customer.getElectricity().setElecDays(0);
        wr.setReqCharges(cost);

        wr.getCust().debitMoney(wr,cost);
        wr.getCust().getNotification().addNotification(wr); 
        JOptionPane.showMessageDialog(null, "The request has been completed", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        

    }//GEN-LAST:event_closeBillButtonActionPerformed

    private void jSlider1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseMoved
        // TODO add your handling code here:
        
        SliderValue.setText(String.valueOf(jSlider1.getValue()));
        SliderValue2.setText(String.valueOf(jSlider2.getValue()));
        cost_10_days=jSlider1.getValue();
        cost_after_10_days=jSlider2.getValue();
    }//GEN-LAST:event_jSlider1MouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJBtn;
    private javax.swing.JLabel SliderValue;
    private javax.swing.JLabel SliderValue2;
    private javax.swing.JButton closeBillButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable receReqJTbl;
    // End of variables declaration//GEN-END:variables
}
