/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Security;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Employee.SecurityEmployee;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Interface.Garbage.CreateStaffJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class SecurityStaffAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecurityStaffAccountJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organisation organization;
    Enterprise enterprise;
    Ecosystem business;

    SecurityStaffAccountJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }

    public void populateTable() {
        
        
        DefaultTableModel dtm = (DefaultTableModel) secStaffJTbl.getModel();
        dtm.setRowCount(0);
        
        for(Employee e: organization.getEmpList().getEmployeeDirectory()){
            if(e.getRole().toString().equals(Role.RoleType.SecurityStaff.getValue())){
                SecurityEmployee sec= (SecurityEmployee) e;
                Object Row[] = new Object[6];
                Row[0] = sec;
                Row[1] = sec.getEmpUserAcc().getUserName();
                Row[2] = sec.getEmpUserAcc().getPassword();
                Row[3] = sec.getWorkQueue().getReqList().size();
                Row[4] = sec.getStreetName();
                Row[5] = sec.getTimeSlot();

                dtm.addRow(Row);
            }
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        secStaffJTbl = new javax.swing.JTable();
        createStaffJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Security Staff Accounts");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        backJBtn.setText("Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        secStaffJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "User Name", "Password", "Assigned Requests", "Location", "TimeSlot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(secStaffJTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 822, 106));

        createStaffJBtn.setText("Create New Security Staff");
        createStaffJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStaffJBtnActionPerformed(evt);
            }
        });
        add(createStaffJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void createStaffJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStaffJBtnActionPerformed
        // TODO add your handling code here:
        CreateSecurityStaffJPanel dcwh = new CreateSecurityStaffJPanel(userProcessContainer,account,organization,enterprise,business);
        userProcessContainer.add("CreateSecurityStaffJPanel",dcwh);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createStaffJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton createStaffJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable secStaffJTbl;
    // End of variables declaration//GEN-END:variables
}
