/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Retailer;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organisation.Grocery.GroceryOrganisation;
import Business.Organisation.Grocery.GroceryProduct;
import Business.Organisation.Organisation;
import Business.Organisation.RetailerOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajaygoel
 */
public class ManageRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRequestsJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    GroceryOrganisation organization;
    Enterprise enterprise;
    Ecosystem business;
    RetailerOrganisation retailerOrganisation;
    GroceryOrganisation groceryOrganisation;
    Date date = new Date();

    ManageRequestsJPanel(JPanel userProcessContainer, UserAccount account, RetailerOrganisation retailerOrganisation, Enterprise enterprise, Ecosystem business, GroceryOrganisation groceryOrganisation) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.groceryOrganisation = groceryOrganisation;
        this.retailerOrganisation = retailerOrganisation;
        process_automatic_requests();
        populate_table();
        System.out.println(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderListJTbl = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Manage Orders");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Order Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

        orderListJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Product", "Sender", "Status", "Requested Date", "Resolved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderListJTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 680, 140));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/products-module-image.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void process_automatic_requests() {
        for (WorkRequest wr : retailerOrganisation.getWorkQueue().getReqList()) {
            if (wr.getStatus().equals("Automatically generated for Retailer")) {
                for (GroceryProduct gpp : groceryOrganisation.getGroceryProductDirectory()) {
                    if (gpp == wr.getGroceryProduct()) {
                        gpp.setAvail(gpp.getAvail() + 70);
                        wr.setMessage("Automatically completed by Retailer");
                        wr.setReceiver(account);
                        wr.setStatus("Automatically completed by Retailer");
                        wr.setResolveDate(date);
                    }
                }

            }
        }
    }

    public void populate_table() {
        DefaultTableModel dtm = (DefaultTableModel) orderListJTbl.getModel();
        dtm.setRowCount(0);
        for (WorkRequest wr : retailerOrganisation.getWorkQueue().getReqList()) {
            if (wr.getStatus().equals("Automatically generated for Retailer") || wr.getStatus().equals("Automatically completed by Retailer")) {
                Object Row[] = new Object[6];
                Row[0] = wr.getMessage();
                Row[1] = wr.getGroceryProduct();
                Row[2] = wr.getSender();
                Row[3] = wr.getStatus();
                Row[4] = wr.getRequestDate();
                Row[5] = wr.getResolveDate();

                dtm.addRow(Row);
            }

        }

    }


    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderListJTbl;
    // End of variables declaration//GEN-END:variables
}
