/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Retailer;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.Grocery.GroceryOrganisation;
import Business.Organisation.Organisation;
import Business.Organisation.RetailerOrganisation;
import Business.UserAccount.UserAccount;
import com.sun.xml.internal.org.jvnet.mimepull.MIMEMessage;
import java.awt.CardLayout;
import javax.swing.JPanel;

//////////////////////////
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessageRemovedException;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author ajaygoel
 */
public class RetailerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RetailerWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    GroceryOrganisation organization;
    Enterprise enterprise;
    Ecosystem business;
    //Organisation organisation1;
    RetailerOrganisation retailerOrganisation;
    GroceryOrganisation groceryOrganisation;
    
    public RetailerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        //this.organisation1= organization;
        this.business=business;
        this.enterprise=enterprise;
        
        nameTxtField.setText(account.getEmployee().getName());
        
        for(Organisation or:enterprise.getOrganisationDirectory().getOrganizationlist())
            {
                for(UserAccount ua:or.getUserAccountDir().getUserAccountDirectory())
                {
                    if(account.getUserName().equals(ua.getUserName()))
                    {
                        retailerOrganisation=(RetailerOrganisation) or;
                    }
                    
                }
//                if(or instanceof RetailerOrganisation)
//                {
//                    retailerOrganisation=(RetailerOrganisation) or;
//                }
                if(or instanceof GroceryOrganisation)
                {
                    groceryOrganisation=(GroceryOrganisation) or;
                }
                
            }
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageProducts = new javax.swing.JButton();
        ManageOrdersBtn = new javax.swing.JButton();
        MailBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Retailer Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 11, 187, -1));

        manageProducts.setText("Manage Products");
        manageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsActionPerformed(evt);
            }
        });
        add(manageProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 187, -1));

        ManageOrdersBtn.setText("Manage Orders");
        ManageOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrdersBtnActionPerformed(evt);
            }
        });
        add(ManageOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 187, -1));

        MailBtn.setText("Mail");
        MailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailBtnActionPerformed(evt);
            }
        });
        add(MailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 187, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Welcome !");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, -1, -1));
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 21, 106, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/supermarket-435452_1280-720x480.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsActionPerformed
        // TODO add your handling code here:
        Interface.Retailer.ManageProductsJPanel irmpjpp = new Interface.Retailer.ManageProductsJPanel(userProcessContainer,account,retailerOrganisation,enterprise,business,groceryOrganisation);
        userProcessContainer.add("ManageProductsJPanel",irmpjpp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductsActionPerformed

    private void ManageOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrdersBtnActionPerformed
        // TODO add your handling code here:
        Interface.Retailer.ManageRequestsJPanel irmpjpp = new Interface.Retailer.ManageRequestsJPanel(userProcessContainer,account,retailerOrganisation,enterprise,business,groceryOrganisation);
        userProcessContainer.add("ManageOrdersJPanel",irmpjpp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrdersBtnActionPerformed

    private void MailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailBtnActionPerformed
        // TODO add your handling code here:
        Properties props = new Properties();
        props.put("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port","465" );
        props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.port","465");
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication("aedproject2018@gmail.com","aedProject2");                
                }
                }
                );
        
        try{
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("aedproject2018@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,InternetAddress.parse("ajaygoel1993@gmail.com,yadav.ank@husky.neu.edu,solanki.h@husky.neu.edu"));
            message.setSubject("Hi, This is me..!!");
            message.setText("Testing AED PRoject mail service..!!");
            Transport.send(message);
            
            JOptionPane.showMessageDialog(null,"message sent");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_MailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MailBtn;
    private javax.swing.JButton ManageOrdersBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton manageProducts;
    private javax.swing.JTextField nameTxtField;
    // End of variables declaration//GEN-END:variables
}
