/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer.Customer;
import Business.Customer.Product;
import Business.Ecosystem;
import Business.Organisation.Grocery.GroceryOrganisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajaygoel
 */
public class ChangeRequirementsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChangeRequirementsJPanel
     */
    JPanel userProcessContainer;
    Customer customer;
    Ecosystem business;
    GroceryOrganisation groceryOrganisation;
    UserAccount userAccount;
    ChangeRequirementsJPanel(JPanel userProcessContainer, Customer customer, Ecosystem business, UserAccount account, GroceryOrganisation groceryOrganisation) {
        initComponents();
        this.groceryOrganisation=groceryOrganisation;
        this.customer=customer;
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.userAccount=userAccount;
        populate_table();
        
    }
    
    public void populate_table()
    {
        DefaultTableModel model = (DefaultTableModel) orderListJTbl.getModel();
        model.setRowCount(0);
        
        for(Product p:customer.getProdList())
        {
            if(p.getAuto_refill()==true)
            {
               Object[] row = new Object[5];
                row[0] = p;
                row[1] = p.getProductQuant();
                row[2] = p.getThreshold();
                row[3] = p.getQuantity_left();
                row[4] = p.getAuto_refill();
                model.addRow(row); 
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderListJTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ThreshholSpinner = new javax.swing.JSpinner();
        SaveBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Change Requirements:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 11, -1, -1));

        orderListJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity ordered", "Thresh-hold value", "Quantity left", "Auto Refill"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderListJTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 733, 126));

        jLabel3.setText("Select Thresh-hold:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 223, -1, -1));
        add(ThreshholSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 220, -1, -1));

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 219, -1, -1));

        backJBtn.setText("Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 219, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/products.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 1080, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        int row = orderListJTbl.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row to change values!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            Product p2 = (Product) orderListJTbl.getValueAt(row,0);
            int thresh = ThreshholSpinner.getComponentCount();
            for(Product p1 : customer.getProdList())
            {
                if(p1==p2)
                {
                    int old_value= p1.getThreshold();
                    p1.setThreshold(thresh);
                    JOptionPane.showMessageDialog(null, "Value changed successfully from "+old_value+" to "+ thresh);
                    populate_table();
                }
                
            }
        }
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn;
    private javax.swing.JSpinner ThreshholSpinner;
    private javax.swing.JButton backJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderListJTbl;
    // End of variables declaration//GEN-END:variables
}
