/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer.Customer;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.EventManagementOrganization;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.Utility.Event;
import Business.WorkQueue.EventMgmtWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ankit
 */
public class CreateNewEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewEventJPanel
     */
    public CreateNewEventJPanel() {
    }
    JPanel userProcessContainer;
    Enterprise enterprise;
    Ecosystem business;
    Customer customer;
    UserAccount account;

    CreateNewEventJPanel(JPanel userProcessContainer, Enterprise enterprise, Ecosystem business, Customer customer, UserAccount account) {
                initComponents();
                
                this.userProcessContainer=userProcessContainer;
                this.enterprise=enterprise;
                this.business=business;
                this.customer=customer;
                this.account=account;
                        
                

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eventCapJTxtField = new javax.swing.JTextField();
        eventNameJTxtField = new javax.swing.JTextField();
        eventDesJTxtField = new javax.swing.JTextField();
        locJTxtField = new javax.swing.JTextField();
        backJBtn = new javax.swing.JButton();
        createEventJBtn = new javax.swing.JButton();
        eventDate = new com.toedter.calendar.JDateChooser();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/party-51.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Create New Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Name: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 120, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Event Description: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 120, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 120, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No of People:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 120, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Location: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 120, -1));
        add(eventCapJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 172, 200, -1));
        add(eventNameJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 58, 200, -1));
        add(eventDesJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 96, 200, -1));
        add(locJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 210, 200, -1));

        backJBtn.setText("Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 248, -1, -1));

        createEventJBtn.setText("Create Event");
        createEventJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventJBtnActionPerformed(evt);
            }
        });
        add(createEventJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 248, -1, -1));
        add(eventDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 134, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        	userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventManagementJPanel manageJPanel = (EventManagementJPanel) component;
        manageJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJBtnActionPerformed

    private void createEventJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventJBtnActionPerformed
        // TODO add your handling code here:
        String name = eventNameJTxtField.getText();
        String desc = eventDesJTxtField.getText();
        Date date = eventDate.getDate();
        
        if (eventCapJTxtField.equals("")||eventDesJTxtField.equals("")||date==null||locJTxtField.equals("")) {
            JOptionPane.showMessageDialog(null, "No field can be empty", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }
        
          if (date.before(new Date())) {
            JOptionPane.showMessageDialog(null, "Date can not be past date.", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        int capacity = 0;
        try {
            capacity = Integer.parseInt(eventCapJTxtField.getText());
        } catch (NumberFormatException numberFormatException) {
              JOptionPane.showMessageDialog(null, "Please enter a number in correct format.", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }
        String loc = locJTxtField.getText();

        Event event = new Event(name, desc, capacity, date, loc);

        customer.addEvent(event);
        EventMgmtWorkRequest wr = new EventMgmtWorkRequest();

        wr.setEvents(event);
        wr.setCust(customer);
        wr.setMessage("Please book the mentioned event.");
        wr.setStatus("OPEN");
        customer.getWorkList().getReqList().add(wr);
        customer.getNotification().addNotification(wr);

        for (Organisation org : enterprise.getOrganisationDirectory().getOrganizationlist()) {
            if (org instanceof EventManagementOrganization) {
                org.getWorkQueue().getReqList().add(wr);

            }
        }
        JOptionPane.showMessageDialog(null, "The event management request has been sent to seciety. It will be resolved soon", "Information", JOptionPane.INFORMATION_MESSAGE);

        eventCapJTxtField.setText("");
        eventDesJTxtField.setText("");
        eventNameJTxtField.setText("");
        locJTxtField.setText("");
        eventDate.setCalendar(null);

    }//GEN-LAST:event_createEventJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton createEventJBtn;
    private javax.swing.JTextField eventCapJTxtField;
    private com.toedter.calendar.JDateChooser eventDate;
    private javax.swing.JTextField eventDesJTxtField;
    private javax.swing.JTextField eventNameJTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField locJTxtField;
    // End of variables declaration//GEN-END:variables
}
