/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Customer.Water;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.Organisation.WaterOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WaterWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Himani Solanki
 */
public class ManageWaterBillsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageWaterBillsJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Ecosystem business;
    WaterOrganisation waterOrganisation1;
    Customer customer;
    CustomerDirectory customerDirectory;
    Water water;
    
    public ManageWaterBillsJPanel(JPanel userProcessContainer, Enterprise enterprise, Ecosystem business, WaterOrganisation waterOrganisation, Customer customer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customer=customer;
        this.business = business;
        
        waterBillNoTextField.setText(String.valueOf(customer.getWaterBill()));
        
        for(Network n:business.getNetworkDirectory())
        {
            for(Enterprise enterprise1 :n.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organisation org:enterprise1.getOrganisationDirectory().getOrganizationlist())
                {
                    if (org instanceof WaterOrganisation)
            
                    {   
                            waterOrganisation1 =(WaterOrganisation) org;
                            break;
                    }
                }
            }
        }
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) waterBillTable.getModel();
        model.setRowCount(0);
        
        for (WorkRequest wr:customer.getWorkList().getReqList())
        {  
//            for(WorkRequest wr3: waterOrganisation1.getWorkQueue().getReqList())
//            {
                if(wr instanceof WaterWorkRequest)
                {
                    WaterWorkRequest ewr = new WaterWorkRequest();
                    ewr = (WaterWorkRequest) wr;
                    Object[] row = new Object[3];
                    row[0] = wr.getCust().getWaterBill();
                    row[1] = ewr.getWater_bill_days();
                    row[2] = ewr.getReqCharges();
                    model.addRow(row);   
                }
//            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        waterBillNoTextField = new javax.swing.JTextField();
        waterBillDaysTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        waterBillTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Water Bill Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 11, -1, -1));

        jLabel2.setText("Water Bill Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("Bill Generation Days");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 91, -1, -1));

        waterBillNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterBillNoTextFieldActionPerformed(evt);
            }
        });
        add(waterBillNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 99, -1));

        waterBillDaysTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterBillDaysTextFieldActionPerformed(evt);
            }
        });
        add(waterBillDaysTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 99, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 126, -1, -1));

        waterBillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Water Bill No", "Days Consumed", "Total Charges"
            }
        ));
        jScrollPane1.setViewportView(waterBillTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 334, 125));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bills.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 950, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void waterBillNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterBillNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterBillNoTextFieldActionPerformed

    private void waterBillDaysTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterBillDaysTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterBillDaysTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWAJPanel cwajp = (CustomerWAJPanel) component;
        cwajp.showJBadgeButton();
        cwajp.populateComboBox();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        //double billno = Double.parseDouble(waterBillNoTextField.getText());
try{
        int days = Integer.parseInt(waterBillDaysTextField.getText());
        
        //customer.setWaterBill(billno);
        customer.getWater().addWaterDays(days);
        
        JOptionPane.showMessageDialog(null, "Days Recorded", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        
        waterBillNoTextField.setEnabled(false);
        waterBillDaysTextField.setEnabled(false);
        waterBillDaysTextField.setText("");
        
        //Automatic generation code
        if(customer.getWater().getWaterDays()>customer.getWater().getWaterThreshold())
        {
        String msg = "Generate Water Bill";
        
        WaterWorkRequest er= new WaterWorkRequest();
        customer.getWorkList().getReqList().add(er);
        
        er.setCust(customer);
        er.setSender(account);
        er.setMessage(msg);
        Date date = new Date();
        er.setRequestDate(date);
        er.setStatus("OPEN");
        er.setWater_bill_days(days);
        
        
        waterOrganisation1.getWorkQueue().getReqList().add(er);
         er.getCust().getNotification().addNotification(er);
        JOptionPane.showMessageDialog(null, "Automatic request for bill has been sent", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        populateTable();
}

catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter number of days in digits.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField waterBillDaysTextField;
    private javax.swing.JTextField waterBillNoTextField;
    private javax.swing.JTable waterBillTable;
    // End of variables declaration//GEN-END:variables
}
