/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Utility.Event;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class ViewEventDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEventDetailsJPanel
     */
    JPanel userProcessContainer;
    Event event;

    ViewEventDetailsJPanel(JPanel userProcessContainer, Event event) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.event=event;
        populateFields();
    }
    
    public void populateFields(){

        DefaultTableModel dtm = (DefaultTableModel) eventAttJTbl.getModel();

        dtm.setRowCount(0);

        Iterator it = event.getAttendeesList().entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry) it.next();
            System.out.println(pair.getKey() + " = " + pair.getValue());

           

                Object[] row = new Object[2];
                row[0] = pair.getKey();
                row[1] = pair.getValue();
      
                dtm.addRow(row);
            }
        
        
        nameJTxtField.setText(event.getEventName());
        descJTxtArea.setText(event.getEventDescription());
        
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");

// Get the date today using Calendar object.
          Date today = event.getEventDate();  
// Using DateFormat format method we can create a string 
// representation of a date with the defined format.
String reportDate = df.format(today);

        
        
        dateJTxtField.setText(reportDate);
        
        locJTxtField.setText(event.getLocation());
        totalSeatsJTxtField.setText(Integer.toString(event.getEventCapacity()));
        totalCapJTxtField.setText(Integer.toString(event.getVacantSeat()));
        adminJTxtField.setText(event.getEventAdmin().toString());
        statusJTxtField.setText(event.getStatus());
        

        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventAttJTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        nameJTxtField = new javax.swing.JTextField();
        dateJTxtField = new javax.swing.JTextField();
        locJTxtField = new javax.swing.JTextField();
        totalCapJTxtField = new javax.swing.JTextField();
        adminJTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        statusJTxtField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descJTxtArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        totalSeatsJTxtField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("View Event Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Attendees List:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        eventAttJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Details", "Seats Booked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(eventAttJTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 112));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Event Name: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Event Description: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 258, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Event Date: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 361, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Event Location: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 399, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Available Seats:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 476, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Admin Details: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 514, 130, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 595, -1, -1));

        nameJTxtField.setEditable(false);
        add(nameJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 220, 166, -1));

        dateJTxtField.setEditable(false);
        add(dateJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 358, 166, -1));

        locJTxtField.setEditable(false);
        add(locJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 396, 166, -1));

        totalCapJTxtField.setEditable(false);
        add(totalCapJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 473, 166, -1));

        adminJTxtField.setEditable(false);
        add(adminJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 511, 166, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Event Status: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 552, 130, -1));

        statusJTxtField.setEditable(false);
        add(statusJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 549, 166, -1));

        descJTxtArea.setEditable(false);
        descJTxtArea.setColumns(20);
        descJTxtArea.setRows(5);
        jScrollPane2.setViewportView(descJTxtArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 256, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total Seats: ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 437, 130, -1));

        totalSeatsJTxtField.setEditable(false);
        add(totalSeatsJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 434, 166, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/event-distribution.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminJTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dateJTxtField;
    private javax.swing.JTextArea descJTxtArea;
    private javax.swing.JTable eventAttJTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locJTxtField;
    private javax.swing.JTextField nameJTxtField;
    private javax.swing.JTextField statusJTxtField;
    private javax.swing.JTextField totalCapJTxtField;
    private javax.swing.JTextField totalSeatsJTxtField;
    // End of variables declaration//GEN-END:variables
}
