/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Customer.Electricity;
import Business.Customer.Garbage;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.ElectricityOrganisation;
import Business.Organisation.Grocery.GroceryOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ElectricityWorkRequest;
import Business.WorkQueue.WaterWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Himani Solanki
 */
public class ViewElectricityBillsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewElectricityBillsJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Ecosystem business;
    ElectricityOrganisation electricityOrganisation1;
    Customer customer;
    CustomerDirectory customerDirectory;
    Electricity electricity;

    ViewElectricityBillsJPanel(JPanel userProcessContainer, Enterprise enterprise, Ecosystem business, ElectricityOrganisation electricityOrganisation,Customer customer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customer=customer;
        this.business = business;
        electricityBillNumberTextField.setText(String.valueOf(customer.getWaterBill()));
        
        
        for(Network n:business.getNetworkDirectory())
        {
            for(Enterprise enterprise1 :n.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organisation org:enterprise1.getOrganisationDirectory().getOrganizationlist())
                {
                    if (org instanceof ElectricityOrganisation)
            
                    {   
                            electricityOrganisation1=(ElectricityOrganisation) org;
                            break;
                    }
                }
            }
        }
        
        
        populateTable();
    }

private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) electricityTable.getModel();
        model.setRowCount(0);
        
        for (WorkRequest wr:customer.getWorkList().getReqList())
        {  
                 if(wr instanceof ElectricityWorkRequest)
                {
                    ElectricityWorkRequest ewr = new ElectricityWorkRequest();
                    ewr = (ElectricityWorkRequest) wr;
                    Object[] row = new Object[3];
                    row[0] = wr.getCust().getElecBill();
                    row[1] = ewr.getElec_bill_days();
                    row[2] = ewr.getReqCharges();
                    model.addRow(row);   
                }

        }
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        electricityTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        electricityBillNumberTextField = new javax.swing.JTextField();
        electricityDaysTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Electricity Bills");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 11, -1, -1));

        electricityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Number", "Days Consumed", "Total Charge"
            }
        ));
        jScrollPane1.setViewportView(electricityTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, -1, 143));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, -1, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 115, -1, -1));

        jLabel2.setText("Electricity Bill Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 54, -1, -1));

        electricityBillNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricityBillNumberTextFieldActionPerformed(evt);
            }
        });
        add(electricityBillNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 51, 109, -1));

        electricityDaysTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricityDaysTextFieldActionPerformed(evt);
            }
        });
        add(electricityDaysTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 77, 109, -1));

        jLabel3.setText("Bill Generation Days");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bills.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWAJPanel cwajp = (CustomerWAJPanel) component;
        cwajp.showJBadgeButton();
        cwajp.populateComboBox();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try{
        int days = Integer.parseInt(electricityDaysTextField.getText());
        
        //customer.setWaterBill(billno);
        customer.getElectricity().addElecDays(days);
        
        JOptionPane.showMessageDialog(null, "Days Recorded", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        
        electricityDaysTextField.setEnabled(false);
        electricityDaysTextField.setText("");
        
        //Automatic generation code
        if(customer.getElectricity().getElecDays()>customer.getElectricity().getElecThreshold())
        {
        String msg = "Generate Electricity Bill";
        
        ElectricityWorkRequest er= new ElectricityWorkRequest();
        customer.getWorkList().getReqList().add(er);
        
        er.setCust(customer);
        er.setSender(account);
        er.setMessage(msg);
        Date date = new Date();
        er.setRequestDate(date);
        er.setStatus("OPEN");
        er.setElec_bill_days(days);
        
        
        electricityOrganisation1.getWorkQueue().getReqList().add(er);
        er.getCust().getNotification().addNotification(er);
        JOptionPane.showMessageDialog(null, "Automatic request for bill has been sent", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        populateTable();
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter number of days in digits.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void electricityBillNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricityBillNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electricityBillNumberTextFieldActionPerformed

    private void electricityDaysTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricityDaysTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electricityDaysTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField electricityBillNumberTextField;
    private javax.swing.JTextField electricityDaysTextField;
    private javax.swing.JTable electricityTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
