/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Garbage;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class GarbageStaffWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GarbageStaffWAJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organisation organization;
    Enterprise enterprise;
    Ecosystem business;

    public GarbageStaffWAJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateOrgTable();
        populateSelfTable();
        
        nameTxtField.setText(account.getEmployee().getName());

    }

    public void populateOrgTable() {

        System.out.println(organization.getWorkQueue().getReqList().size());

        DefaultTableModel dtm = (DefaultTableModel) orgReqJTable.getModel();
        //  productCatalogTbl.getColumn("Image").setCellRenderer(new ManageProductsJPanel.LabelRenderer());
        dtm.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getReqList()) {

            Object Row[] = new Object[5];
            Row[0] = wr.getCust();
            Row[1] = wr;
            Row[2] = wr.getMessage();
            Row[3] = wr.getStatus();
            Row[4] = wr.getReceiver();

            dtm.addRow(Row);
        }

    }

    public void populateSelfTable() {

        System.out.println(account.getWorkQueue().getReqList().size());

        DefaultTableModel dtm = (DefaultTableModel) selfReqJTable.getModel();
        //  productCatalogTbl.getColumn("Image").setCellRenderer(new ManageProductsJPanel.LabelRenderer());
        dtm.setRowCount(0);

        for (WorkRequest wr : account.getWorkQueue().getReqList()) {

            Object Row[] = new Object[4];
            Row[0] = wr.getCust();
            Row[1] = wr;
            Row[2] = wr.getMessage();
            Row[3] = wr.getStatus();

            dtm.addRow(Row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orgReqJTable = new javax.swing.JTable();
        completeRequestJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        assignToMeJBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selfReqJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Garbage Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 0, -1, -1));

        orgReqJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Request Date", "Message", "Status", "Assigned To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgReqJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 696, 152));

        completeRequestJBtn.setText("Complete");
        completeRequestJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeRequestJBtnActionPerformed(evt);
            }
        });
        add(completeRequestJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 501, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("All Work Request Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        assignToMeJBtn.setText("Assign to Me");
        assignToMeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJBtnActionPerformed(evt);
            }
        });
        add(assignToMeJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 255, -1, -1));

        selfReqJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Request Date", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(selfReqJTable);
        if (selfReqJTable.getColumnModel().getColumnCount() > 0) {
            selfReqJTable.getColumnModel().getColumn(3).setHeaderValue("Status");
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 331, 696, 152));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Requests Assigned to me");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 296, -1, -1));
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 4, 106, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Welcome !");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Garbage-Collection.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJBtnActionPerformed
        // TODO add your handling code here:

        int row = orgReqJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest wr = (WorkRequest) orgReqJTable.getValueAt(row, 1);

        if (wr.getStatus().equals("CLOSED")) {
            JOptionPane.showMessageDialog(null, "The request is already completed", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (wr.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(null, "The request is already assigned to you", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        wr.setReceiver(account);
        account.getWorkQueue().getReqList().add(wr);
                wr.getCust().getNotification().addNotification(wr);

        JOptionPane.showMessageDialog(null, "The request has been successfully assigned to you", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        populateOrgTable();
        populateSelfTable();


    }//GEN-LAST:event_assignToMeJBtnActionPerformed

    private void completeRequestJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeRequestJBtnActionPerformed
        // TODO add your handling code here:
        
                      int row = selfReqJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        WorkRequest wr= (WorkRequest)selfReqJTable.getValueAt(row, 1);
        if(wr.getStatus().equals("CLOSED")){
             JOptionPane.showMessageDialog(null, "This request has already been closed", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        wr.getCust().getGarbageDetails().setGarbageContainerWeight(0);
        wr.setStatus("CLOSED");
        wr.setMessage("The garbage bin has been cleared");
        Date resolveDate= new Date();
        wr.setResolveDate(resolveDate);
        
        wr.getCust().debitMoney(wr, 10.00);
        wr.getCust().getNotification().addNotification(wr);

        JOptionPane.showMessageDialog(null, "The request has been completed. Cleaning charge- $ 10.00", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);

        populateOrgTable();
        populateSelfTable();
    }//GEN-LAST:event_completeRequestJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJBtn;
    private javax.swing.JButton completeRequestJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTable orgReqJTable;
    private javax.swing.JTable selfReqJTable;
    // End of variables declaration//GEN-END:variables
}
