/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Garbage;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ajaygoel
 */
public class GarbageWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GarbageWAJPanel
     */

    
    JPanel userProcessContainer;
    UserAccount account;
    Organisation organization;
    Enterprise enterprise;
    Ecosystem business;

    public GarbageWAJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
    
        
                initComponents();
                this.userProcessContainer=userProcessContainer;
                this.account=account;
                this.organization=organization;
                this.business=business;
                this.enterprise=enterprise;
            nameTxtField.setText(account.getEmployee().getName());    

    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageGarbageRequestsBtn = new javax.swing.JButton();
        ManageAcc = new javax.swing.JButton();
        nameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 102, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Garbage Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 11, 236, -1));

        ManageGarbageRequestsBtn.setText("Manage Garbage Requests");
        ManageGarbageRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageGarbageRequestsBtnActionPerformed(evt);
            }
        });
        add(ManageGarbageRequestsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, 663, -1));

        ManageAcc.setText("Manage Accounts");
        ManageAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccActionPerformed(evt);
            }
        });
        add(ManageAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 663, -1));
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 15, 106, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Welcome !");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/recycling-paper-glass-plastic.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageGarbageRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageGarbageRequestsBtnActionPerformed
        // TODO add your handling code here:
        Interface.Garbage.GarbageRequestsJPanel dcwh = new Interface.Garbage.GarbageRequestsJPanel(userProcessContainer,account,organization,enterprise,business);
        userProcessContainer.add("GarbageRequestsJPanel",dcwh);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageGarbageRequestsBtnActionPerformed

    private void ManageAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccActionPerformed
        // TODO add your handling code here:

        Interface.Garbage.GarbageAccountJPanel dcwhq = new Interface.Garbage.GarbageAccountJPanel(userProcessContainer,account,organization,enterprise,business);
        userProcessContainer.add("Interface.Supplier.UpdateSupplierAccountsJPanel",dcwhq);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAcc;
    private javax.swing.JButton ManageGarbageRequestsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTxtField;
    // End of variables declaration//GEN-END:variables
}
