/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ajaygoel
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;
    Ecosystem business;
    Organisation organisation;


    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.enterprise=enterprise;
        this.organisation= organization;
        populateTree();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ManageCustomersJBtn = new javax.swing.JButton();
        ManageSocietyBtn = new javax.swing.JButton();
        ManageEnterpriseAdminBtn = new javax.swing.JButton();
        ManageEnterpriseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();

        jButton15.setText("jButton1");

        setBackground(new java.awt.Color(0, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADMINISTRATOR");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 0, -1, -1));

        ManageCustomersJBtn.setText("Manage Customers");
        ManageCustomersJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCustomersJBtnActionPerformed(evt);
            }
        });
        add(ManageCustomersJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 217, 298, -1));

        ManageSocietyBtn.setText("Manage Network");
        ManageSocietyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSocietyBtnActionPerformed(evt);
            }
        });
        add(ManageSocietyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 94, 298, -1));

        ManageEnterpriseAdminBtn.setText("Mange Enterprise Admin");
        ManageEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseAdminBtnActionPerformed(evt);
            }
        });
        add(ManageEnterpriseAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 176, 298, -1));

        ManageEnterpriseBtn.setText("Mange Enterprise");
        ManageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseBtnActionPerformed(evt);
            }
        });
        add(ManageEnterpriseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 135, 298, -1));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        JTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                JTreevalueChangedAction(evt);
            }
        });
        jScrollPane1.setViewportView(JTree);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 47, 157, 718));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/admin.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 460));
    }// </editor-fold>//GEN-END:initComponents

    
    
        public void populateTree() {
        
        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();

        
        
        ArrayList<Network> networkList = business.getNetworkDirectory();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organisation> organizationList;
        Network network;
        Enterprise enterprise;
        Organisation organization;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        for (int i = 0; i < networkList.size(); i++) {
            network = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);

            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();

            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getEnterpriseName());
                networkNode.insert(enterpriseNode, j);

                organizationList = enterprise.getOrganisationDirectory().getOrganizationlist();
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getOrgName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }

        model.reload();
    }
        
        
        
    private void ManageSocietyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSocietyBtnActionPerformed
        // TODO add your handling code here:
        Interface.Admin.ManageSocietyNetworkJPanel msnwjp = new Interface.Admin.ManageSocietyNetworkJPanel(userProcessContainer, account, organisation, enterprise, business);
        userProcessContainer.add("ManageSocietyNetworkJPanel",msnwjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageSocietyBtnActionPerformed

    private void ManageEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseAdminBtnActionPerformed
        // TODO add your handling code here:
        Interface.Admin.ManageEnterpriseAdminJPanel iamejp = new Interface.Admin.ManageEnterpriseAdminJPanel(userProcessContainer, account, organisation, enterprise, business);
        userProcessContainer.add("ManageSocietyNetworkJPanel",iamejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEnterpriseAdminBtnActionPerformed

    private void ManageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        Interface.Admin.ManageEnterpriseJPanel iamejpp = new Interface.Admin.ManageEnterpriseJPanel(userProcessContainer, account, organisation, enterprise, business);
        userProcessContainer.add("ManageEnterpriseJPanel",iamejpp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEnterpriseBtnActionPerformed

    private void JTreevalueChangedAction(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_JTreevalueChangedAction
//        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
//        if (selectedNode != null) {
//            selectedNodeJLabel.setText(selectedNode.toString());
//        }
    }//GEN-LAST:event_JTreevalueChangedAction

    private void ManageCustomersJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCustomersJBtnActionPerformed
        // TODO add your handling code here:
        Interface.Admin.ManageCustomerWAJPanel iamcwajp = new Interface.Admin.ManageCustomerWAJPanel(userProcessContainer, enterprise,business);
        userProcessContainer.add("ManageCustomerWAJPanel", iamcwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageCustomersJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JButton ManageCustomersJBtn;
    private javax.swing.JButton ManageEnterpriseAdminBtn;
    private javax.swing.JButton ManageEnterpriseBtn;
    private javax.swing.JButton ManageSocietyBtn;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
