/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Customer.Customer;
import Business.Ecosystem;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ajaygoel
 */
public class ViewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerJPanel
     */
    
    JPanel userProcessContainer;
    Customer customer;
    Ecosystem business;

    ViewCustomerJPanel(JPanel userProcessContainer, Customer cr,Ecosystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.customer=cr;
        this.business=business;
        
        
        FirstNameTxtField.setEnabled(false);
        LastNameTxtField.setEnabled(false);
        LocationTxtField.setEnabled(false);
        HouseNoTextField.setEnabled(false);
        CreditCardTxtField.setEnabled(false);
        PaymentComboBox.setEnabled(false);
        UserNameTxtField.setEnabled(false);
        PasswordTxtField.setEnabled(false);
        MobiletxtField.setEnabled(false);
        NetworkComboBox.setEnabled(false);
        EmailTxtField.setEnabled(false);
        Electxtfield.setEnabled(false);
        WaterTextField.setEnabled(false);
        
        
        FirstNameTxtField.setText(customer.getFirst_name());
        LastNameTxtField.setText(customer.getLast_name());
        LocationTxtField.setText(customer.getLocation());
        HouseNoTextField.setText(String.valueOf(customer.getHouse_no()));
        CreditCardTxtField.setText(String.valueOf(customer.getCredit_card_no()));
        PaymentComboBox.setActionCommand(customer.getMode_of_payment());
        UserNameTxtField.setText(customer.getUserAcc().getUserName());
        PasswordTxtField.setText(customer.getUserAcc().getPassword());
        MobiletxtField.setText(String.valueOf(customer.getMobile_no()));
        //NetworkComboBox.setActionCommand(customer.getNetwork_name());
        EmailTxtField.setText(customer.getE_mail());
        Electxtfield.setText(String.valueOf(customer.getElecBill()));
        WaterTextField.setText(String.valueOf(customer.getWaterBill()));
        
        for(Network n :business.getNetworkDirectory())
        {
            for(Customer c:n.getCustomerDirectory().getCustList())
            {
                if(c.getUserAcc().getUserName().equals(customer.getUserAcc().getUserName()))
                {
                    NetworkComboBox.addItem(n);
                }
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        PaymentComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        UserNameTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PasswordTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MobiletxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        NetworkComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EmailTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FirstNameTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LastNameTxtField = new javax.swing.JTextField();
        LocationTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        HouseNoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CreditCardTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Electxtfield = new javax.swing.JTextField();
        WaterTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Mode of Payment");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 260, 100, -1));

        PaymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Net Banking", "Credit Card", "Debit Card", " " }));
        add(PaymentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 257, 200, -1));

        jLabel8.setText("User name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 100, -1));
        add(UserNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 295, 200, -1));

        jLabel9.setText("Password:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 336, 100, -1));
        add(PasswordTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 333, 200, -1));

        jLabel4.setText("Mobile Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 374, 100, -1));
        add(MobiletxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 371, 200, -1));

        jLabel13.setText("Society Name");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 412, 100, -1));

        add(NetworkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 409, 200, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Customer Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, -1, -1));

        jLabel11.setText("E-mail:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 450, 100, -1));
        add(EmailTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 447, 200, -1));

        jLabel2.setText("First Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 70, 100, -1));
        add(FirstNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 67, 200, -1));

        jLabel6.setText("Last Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 108, 100, -1));
        add(LastNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 105, 200, -1));
        add(LocationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 143, 200, -1));

        jLabel5.setText("Location");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 143, 100, -1));

        jLabel10.setText("House No:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 184, 100, -1));
        add(HouseNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 181, 200, -1));

        jLabel3.setText("Credit Card Number:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 222, 100, -1));
        add(CreditCardTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 219, 200, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 605, -1, -1));

        jLabel12.setText("Electricity Bill No.");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 538, 100, -1));

        jLabel14.setText("Water Bill No.");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 573, 100, -1));
        add(Electxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 535, 193, -1));
        add(WaterTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 567, 193, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CreditCardTxtField;
    private javax.swing.JTextField Electxtfield;
    private javax.swing.JTextField EmailTxtField;
    private javax.swing.JTextField FirstNameTxtField;
    private javax.swing.JTextField HouseNoTextField;
    private javax.swing.JTextField LastNameTxtField;
    private javax.swing.JTextField LocationTxtField;
    private javax.swing.JTextField MobiletxtField;
    private javax.swing.JComboBox NetworkComboBox;
    private javax.swing.JTextField PasswordTxtField;
    private javax.swing.JComboBox<String> PaymentComboBox;
    private javax.swing.JTextField UserNameTxtField;
    private javax.swing.JTextField WaterTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
