/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Government;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.Organisation.OrganisationDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class CreateGovernmentAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateGovernmentAdminJPanel
     */
    private OrganisationDirectory organizationDir;
    private JPanel userProcessContainer;
    private Enterprise enterprise;

    CreateGovernmentAdminJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = enterprise.getOrganisationDirectory();
        this.enterprise = enterprise;
        populateTable();
        populateRoleComboBox();
        populateOrgComboBox();
    }

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) OrganizationJTable.getModel();

        model.setRowCount(0);

        for (Organisation organization : enterprise.getOrganisationDirectory().getOrganizationlist()) {
            for (Employee ee : organization.getEmpList().getEmployeeDirectory()) {
                Object row[] = new Object[3];
                row[0] = ee.getEmpUserAcc().getUserName();
                row[1] = ee.getEmpUserAcc().getRole();
                row[2] = ee.getEmpUserAcc().getPassword();
                model.addRow(row);
            }
        }
                     
    }

    public void populateRoleComboBox() {
        RoleComboBox.removeAllItems();
        for (Organisation o : organizationDir.getOrganizationlist()) {
            for (Role role : o.getSupportedRole()) {
                RoleComboBox.addItem(role);
            }

        }
    }

    public void populateOrgComboBox() {
        OrganisationComboBox.removeAllItems();
        for (Organisation o : organizationDir.getOrganizationlist()) {
            OrganisationComboBox.addItem(o);

        }
    }
    
    public void populateRoleComboBox2(Organisation organisation)
    {   
        RoleComboBox.removeAllItems();
        for(Role r:organisation.getSupportedRole())
        {
            RoleComboBox.addItem(r);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrganizationJTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        OrganisationComboBox = new javax.swing.JComboBox();
        usernameJTextField = new javax.swing.JTextField();
        passwordJPasswordField = new javax.swing.JPasswordField();
        nameTXT = new javax.swing.JTextField();
        RoleComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Role", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrganizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 51, 523, 95));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Manage Organisations Admin");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 11, -1, -1));

        jLabel1.setText("Organisation:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 221, -1, -1));

        OrganisationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrganisationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OrganisationComboBoxItemStateChanged(evt);
            }
        });
        OrganisationComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrganisationComboBoxMouseClicked(evt);
            }
        });
        OrganisationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganisationComboBoxActionPerformed(evt);
            }
        });
        OrganisationComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OrganisationComboBoxKeyPressed(evt);
            }
        });
        add(OrganisationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 218, 134, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 250, 128, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 281, 128, -1));
        add(nameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 324, 128, -1));

        RoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleComboBoxActionPerformed(evt);
            }
        });
        add(RoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 368, 134, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 406, 282, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 406, -1, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 256, -1, -1));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 284, -1, -1));

        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 319, -1, 31));

        jLabel7.setText("Role");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 371, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void OrganisationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganisationComboBoxActionPerformed
        // TODO add your handling code here:
        
                Organisation oo = (Organisation) OrganisationComboBox.getSelectedItem();
                if(oo!=null)
                {
                    populateRoleComboBox2(oo);
                }
                

    }//GEN-LAST:event_OrganisationComboBoxActionPerformed

    private void RoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleComboBoxActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Role role = (Role) RoleComboBox.getSelectedItem();
        Organisation o = (Organisation) OrganisationComboBox.getSelectedItem();
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String name = nameTXT.getText();

        Employee employee = o.getEmpList().createEmployee(name, role);
        UserAccount ua = new UserAccount();
        ua.setEmployee(employee);
        ua.setPassword(password);
        ua.setRole(role);
        ua.setUserName(username);
        o.getUserAccountDir().addUserAccount(ua);
        employee.setEmpUserAcc(ua);
        
        JOptionPane.showMessageDialog(null, "Added Successfully..!!");
        usernameJTextField.setText("");
        nameTXT.setText("");
        passwordJPasswordField.setText("");

        populateTable();
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        //Component[] componentArray = userProcessContainer.getComponents();
        //Component component = componentArray[componentArray.length - 1];
        //SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void OrganisationComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrganisationComboBoxMouseClicked
        // TODO add your handling code here:                
    }//GEN-LAST:event_OrganisationComboBoxMouseClicked

    private void OrganisationComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OrganisationComboBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrganisationComboBoxKeyPressed

    private void OrganisationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OrganisationComboBoxItemStateChanged
        // TODO add your handling code here:
//        Organisation oo = (Organisation) OrganisationComboBox.getSelectedItem();
//        
//        for(Role r:oo.getSupportedRole())
//        {
//            RoleComboBox.addItem(r);
//        }
    }//GEN-LAST:event_OrganisationComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox OrganisationComboBox;
    private javax.swing.JTable OrganizationJTable;
    private javax.swing.JComboBox RoleComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
