/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Market;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Grocery.GroceryOrganisation;
import Business.Organisation.Organisation;
import Business.Organisation.OrganisationDirectory;
import Business.Role.CustomerRole;
import Business.Role.DeliveryAdmin;
import Business.Role.MarketAdmin;
import Business.Role.MarketEnterpriseRole;
import Business.Role.RetailerAdmin;
import Business.Role.Role;
import static Business.Role.Role.RoleType.MarketAdmin;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajaygoel
 */
public class CreateMarketOrganisationAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMarketOrganisationAdminJPanel
     */
//    JPanel userProcessContainer;
//    Enterprise enterprise;
//    UserAccount account;
//    Ecosystem business;
//    Organisation organisation;
    
    private OrganisationDirectory organizationDir;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    //Organisation organisation1;

//    public CreateMarketOrganisationAdminJPanel(JPanel userProcessContainer, UserAccount account,  Organisation organisation, Enterprise enterprise, Ecosystem business) {
//        
////        this.userProcessContainer=userProcessContainer;
////        this.account=account;
////        this.business=business;
////        this.enterprise=enterprise;
////        this.organisation= organisation;
//        
//        //organisation1 = new GroceryOrganisation();
//        
//        //organisation1 = enterprise.getOrganisationDirectory().createMarketOrganisation(Organisation.MarketType.MarketAdmin);
//        //populateTable();
//        
//    }

    CreateMarketOrganisationAdminJPanel(JPanel userProcessContainer, OrganisationDirectory organisationDirectory) {
        
        
    }

    CreateMarketOrganisationAdminJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = enterprise.getOrganisationDirectory();
        this.enterprise= enterprise;
        populateTable();
        populateRoleComboBox();
        populateOrgComboBox();
    }

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) OrganizationJTable.getModel();

        model.setRowCount(0);

        for (Organisation organization : enterprise.getOrganisationDirectory().getOrganizationlist()) {
            for (Employee ee : organization.getEmpList().getEmployeeDirectory()) {
                Object row[] = new Object[3];
                row[0] = ee.getEmpUserAcc().getUserName();
                row[1] = ee.getEmpUserAcc().getRole();
                row[2]= ee.getEmpUserAcc().getPassword();
                model.addRow(row);
            }
        }
    }


    public void populateRoleComboBox() {
        RoleComboBox.removeAllItems();
        for(Organisation o: organizationDir.getOrganizationlist())
        {
            for(Role role: o.getSupportedRole())
           {
                RoleComboBox.addItem(role);
           }
            
        }
    }   
    
    public void populateOrgComboBox()
    {
        OrganisationComboBox.removeAllItems();
        for(Organisation o: organizationDir.getOrganizationlist())
        {
                OrganisationComboBox.addItem(o);
            
        }
    }
    
    public void populateComboBox2(Organisation organisation)
    {   
        RoleComboBox.removeAllItems();
        for(Role r:organisation.getSupportedRole())
        {
            RoleComboBox.addItem(r);
        }
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrganizationJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        OrganisationComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Role", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrganizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 64, 523, 95));

        jLabel1.setText("Organisation:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 183, -1, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 215, -1, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 203, 128, -1));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 240, -1, 15));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 235, 128, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 365, 282, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 365, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Manage Organisations Admin");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 24, -1, -1));

        RoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleComboBoxActionPerformed(evt);
            }
        });
        add(RoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 310, 134, -1));

        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 261, -1, 31));
        add(nameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 261, 128, -1));

        OrganisationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrganisationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganisationComboBoxActionPerformed(evt);
            }
        });
        add(OrganisationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 177, 134, -1));

        jLabel7.setText("Role");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

            Role role=  (Role) RoleComboBox.getSelectedItem();
            Organisation o = (Organisation) OrganisationComboBox.getSelectedItem();
            String username = usernameJTextField.getText();
            String password = String.valueOf(passwordJPasswordField.getPassword());
            String name = nameTXT.getText();

            Employee employee = o.getEmpList().createEmployee(name,role);
            //employee.setRole(role);
            UserAccount ua = new UserAccount();
            ua.setEmployee(employee);
            ua.setPassword(password);
            ua.setRole(role);
            ua.setUserName(username);
            o.getUserAccountDir().addUserAccount(ua);
            employee.setEmpUserAcc(ua);
            JOptionPane.showMessageDialog(null, "Added Successfully..!!");
            usernameJTextField.setText("");
            nameTXT.setText("");
            passwordJPasswordField.setText("");
            populateTable();

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void RoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleComboBoxActionPerformed

    private void OrganisationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganisationComboBoxActionPerformed
        // TODO add your handling code here:
        
         Organisation oo = (Organisation) OrganisationComboBox.getSelectedItem();
                if(oo!=null)
                {
                    populateComboBox2(oo);
                }
                
    }//GEN-LAST:event_OrganisationComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox OrganisationComboBox;
    private javax.swing.JTable OrganizationJTable;
    private javax.swing.JComboBox RoleComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
