/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Delivery;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organisation.DeliveryOrganisation;
import Business.Organisation.Organisation;
import Business.Role.DeliveryManRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ajaygoel
 */
public class CreateDeliveryEmployeesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDeliveryEmployeesJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Ecosystem business;
    DeliveryOrganisation deliveryOrganisation;

    CreateDeliveryEmployeesJPanel(JPanel userProcessContainer, UserAccount account, DeliveryOrganisation deliveryOrganisation, Enterprise enterprise, Ecosystem business) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.deliveryOrganisation = deliveryOrganisation;
        IDField.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        passwordTxtField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create New Staff Profile:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Staff Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 105, 160, 30));

        nameField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 107, 210, 23));

        IDField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 153, 210, 21));

        createButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createButton.setText("Add Person");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 316, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Staff ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 153, 160, 30));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 316, -1, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 201, -1, -1));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 233, -1, 31));

        usernameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJTextFieldActionPerformed(evt);
            }
        });
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 192, 222, -1));
        add(passwordTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 238, 222, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String name = nameField1.getText();
        String Username = usernameJTextField.getText();
        String Password = passwordTxtField.getText();
        

       if (business.checkIfUsernameIsUnique(Username)) {
            Employee emp = deliveryOrganisation.getEmpList().createEmployee(name, new DeliveryManRole());
            UserAccount ua = new UserAccount();
            ua.setEmployee(emp);
            ua.setUserName(Username);
            ua.setPassword(Password);
            ua.setRole(new DeliveryManRole());
            deliveryOrganisation.getUserAccountDir().addUserAccount(ua);
            emp.setEmpUserAcc(ua);
            IDField.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Employee successfully added", "Information", JOptionPane.INFORMATION_MESSAGE);
            nameField1.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter different user Name", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Interface.Delivery.ManageAccountsDeliveryJPanel el = (Interface.Delivery.ManageAccountsDeliveryJPanel) component;
        el.populate_table();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void usernameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameField1;
    private javax.swing.JTextField passwordTxtField;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
