/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Delivery;

import Business.Customer.Customer;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.DeliveryOrganisation;
import Business.Organisation.Grocery.GroceryOrganisation;
import Business.Organisation.Organisation;
import Business.Organisation.RetailerOrganisation;
import Business.UserAccount.UserAccount;
import Business.Utility.Wallet;
import Interface.Market.MarketWalletDetails;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ajaygoel
 */
public class DeliveryAdminWAJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryAdminWAJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Ecosystem business;
    Organisation organisation;
    DeliveryOrganisation deliveryOrganisation;
    
    public DeliveryAdminWAJPanel(JPanel userProcessContainer, UserAccount account, Organisation organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.enterprise=enterprise;
        this.organisation= organization;
        
        
        for(Network n: business.getNetworkDirectory())
        {
            for(Enterprise ee:n.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organisation or:ee.getOrganisationDirectory().getOrganizationlist())
            {   
                if(or instanceof DeliveryOrganisation)
                {
                    deliveryOrganisation=(DeliveryOrganisation) or;
                }
                
            }
            }
        }
         
      nameTxtField.setText(account.getEmployee().getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageAcconts = new javax.swing.JButton();
        ManageOrdersBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Delivery work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 0, -1, -1));

        ManageAcconts.setText("Manage Accounts");
        ManageAcconts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccontsActionPerformed(evt);
            }
        });
        add(ManageAcconts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 187, -1));

        ManageOrdersBtn.setText("Manage Orders");
        ManageOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrdersBtnActionPerformed(evt);
            }
        });
        add(ManageOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 187, -1));

        jButton1.setText("Manage Wallet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 187, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Welcome !");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 15, 106, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/delivery-truck-icon.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAccontsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccontsActionPerformed
        // TODO add your handling code here:

        Interface.Delivery.ManageAccountsDeliveryJPanel idmadp = new Interface.Delivery.ManageAccountsDeliveryJPanel(userProcessContainer,account,organisation,enterprise,business);
        userProcessContainer.add("ManageAccountsDeliveryJPanel",idmadp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageAccontsActionPerformed

    private void ManageOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrdersBtnActionPerformed
        // TODO add your handling code here:
        Interface.Delivery.ManageDeliveryOrdersJPanel idmdojp = new Interface.Delivery.ManageDeliveryOrdersJPanel(userProcessContainer,account,organisation,enterprise,business);
        userProcessContainer.add("ManageDeliveryOrdersJPanel",idmdojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrdersBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Wallet wallet= deliveryOrganisation.getWalletObj();
        String name= deliveryOrganisation.getOrgName().toString();
        ManageDeliveryWalletJPanel mdwjpp = new ManageDeliveryWalletJPanel(name, wallet, userProcessContainer);
        userProcessContainer.add("mdwjpp", mdwjpp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAcconts;
    private javax.swing.JButton ManageOrdersBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameTxtField;
    // End of variables declaration//GEN-END:variables
}
